version: Build {build}
branches:
  only:
  - master
  - dev
image: Visual Studio 2022
environment:
  PUBLISH_CLIENTSECRET:
    secure: Q0v+RZeL5HORLaCOBP0ImyA+xBRa8HLFixqd+I4MrV0MKwqae5f6W9CL4Liuh86i
install:
- ps: .\AppVeyor\Install.ps1
build_script:
- ps: .\AppVeyor\Build.ps1
deploy_script:
- ps: .\AppVeyor\Publish.ps1
cache:
- '%USERPROFILE%\.nuget\packages -> **\*.csproj'
artifacts:
- path: '**/*.msixupload'
  name: AppPackages
